<a href="https://colab.research.google.com/github/ajaykumar080286/Pandas/blob/main/GroupBy_method.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import pandas as pd
import numpy as np

In [25]:
df=pd.read_csv('Fortune_1000.csv')

In [26]:
df.head()

,company,rank,rank_change,revenue,profit,num. of employees,sector,city,state,newcomer,ceo_founder,ceo_woman,profitable,prev_rank,CEO,Website,Ticker,Market Cap
0,Walmart,1,0.0,572754.0,13673.0,2300000.0,Retailing,Bentonville,AR,no,no,no,yes,1.0,C. Douglas McMillon,https://www.stock.walmart.com,WMT,352037
1,Amazon,2,0.0,469822.0,33364.0,1608000.0,Retailing,Seattle,WA,no,no,no,yes,2.0,Andrew R. Jassy,www.amazon.com,AMZN,1202717
2,Apple,3,0.0,365817.0,94680.0,154000.0,Technology,Cupertino,CA,no,no,no,yes,3.0,Timothy D. Cook,www.apple.com,AAPL,2443962
3,CVS Health,4,0.0,292111.0,7910.0,258000.0,Health Care,Woonsocket,RI,no,no,yes,yes,4.0,Karen Lynch,https://www.cvshealth.com,CVS,125204
4,UnitedHealth Group,5,0.0,287597.0,17285.0,350000.0,Health Care,Minnetonka,MN,no,no,no,yes,5.0,Andrew P. Witty,www.unitedhealthgroup.com,UNH,500468

In [27]:
sectors=df.groupby('sector')

In [28]:
sectors

In [29]:
len(df['sector'])

1000

In [30]:
len(df['company'])

1000

In [31]:
len(sectors)

21

In [32]:
sectors.size().sort_values(ascending=False)

sector
Financials                       166
Technology                       121
Energy                           100
Health Care                       77
Retailing                         77
Business Services                 52
Industrials                       50
Materials                         46
Transportation                    35
Food, Beverages & Tobacco         34
Engineering & Construction        32
Wholesalers                       31
Chemicals                         29
Hotels, Restaurants & Leisure     28
Media                             28
Household Products                23
Motor Vehicles & Parts            20
Aerospace & Defense               17
Apparel                           16
Food & Drug Stores                 9
Telecommunications                 9
dtype: int64

In [33]:
sectors.size().sort_values(ascending=False).head()  #top 5 company

sector
Financials     166
Technology     121
Energy         100
Health Care     77
Retailing       77
dtype: int64

In [34]:
df.head(2)

,company,rank,rank_change,revenue,profit,num. of employees,sector,city,state,newcomer,ceo_founder,ceo_woman,profitable,prev_rank,CEO,Website,Ticker,Market Cap
0,Walmart,1,0.0,572754.0,13673.0,2300000.0,Retailing,Bentonville,AR,no,no,no,yes,1.0,C. Douglas McMillon,https://www.stock.walmart.com,WMT,352037
1,Amazon,2,0.0,469822.0,33364.0,1608000.0,Retailing,Seattle,WA,no,no,no,yes,2.0,Andrew R. Jassy,www.amazon.com,AMZN,1202717

In [35]:
sectors.first()

,company,rank,rank_change,revenue,profit,num. of employees,city,state,newcomer,ceo_founder,ceo_woman,profitable,prev_rank,CEO,Website,Ticker,Market Cap
sector,,,,,,,,,,,,,,,,,
Aerospace & Defense,Lockheed Martin,55,-6.0,67044.0,6315.0,114000.0,Bethesda,MD,no,no,no,yes,49.0,James D. Taiclet Jr.,www.lockheedmartin.com,LMT,103510
Apparel,Nike,83,2.0,44538.0,5727.0,73300.0,Beaverton,OR,no,no,no,yes,85.0,John J. Donahoe II,www.nike.com,NKE,171840
Business Services,PayPal,143,-9.0,25371.0,4169.0,30900.0,San Jose,CA,no,no,no,yes,134.0,Daniel Schulman,https://www.paypal.com,PYPL,99538
Chemicals,Dow,64,18.0,54968.0,6311.0,35700.0,Midland,MI,no,no,no,yes,82.0,James R. Fitterling,www.dow.com,DOW,38189
Energy,Exxon Mobil,6,4.0,285640.0,23040.0,63000.0,Irving,TX,no,no,no,yes,10.0,Darren W. Woods,www.exxonmobil.com,XOM,371841
Engineering & Construction,D.R. Horton,124,24.0,27774.2,4175.8,11788.0,Arlington,TX,no,no,no,yes,148.0,David Auld,https://www.drhorton.com,DHI,24313
Financials,Berkshire Hathaway,7,-1.0,276094.0,89795.0,372000.0,Omaha,NE,no,no,no,yes,6.0,Warren E. Buffett,www.berkshirehathaway.com,BRKA,625468
Food & Drug Stores,Walgreens Boots Alliance,18,-2.0,148579.0,2542.0,258500.0,Deerfield,IL,no,no,yes,yes,16.0,Roz Brewer,www.walgreensbootsalliance.com,WBA,33360
"Food, Beverages & Tobacco",Archer Daniels Midland,38,13.0,85249.0,2709.0,39979.0,Chicago,IL,no,no,no,yes,51.0,Juan R. Luciano,www.adm.com,ADM,41545
Health Care,CVS Health,4,0.0,292111.0,7910.0,258000.0,Woonsocket,RI,no,no,yes,yes,4.0,Karen Lynch,https://www.cvshealth.com,CVS,125204
"Hotels, Restaurants & Leisure",Starbucks,120,5.0,29060.6,4199.3,383000.0,Seattle,WA,no,yes,no,yes,125.0,Howard D. Schultz,www.starbucks.com,SBUX,94677
Household Products,Procter & Gamble,47,-4.0,76118.0,14306.0,101000.0,Cincinnati,OH,no,no,no,yes,43.0,Jon R. Moeller,www.pg.com,PG,345595
Industrials,General Electric,48,-10.0,74196.0,-6520.0,168000.0,Boston,MA,no,no,no,no,38.0,H. Lawrence Culp Jr.,www.ge.com,GE,73458
Materials,Nucor,98,51.0,36483.9,6827.5,28800.0,Charlotte,NC,no,no,no,yes,149.0,Leon J. Topalian,www.nucor.com,NUE,31183
Media,Walt Disney,53,-3.0,67418.0,1995.0,171000.0,Burbank,CA,no,no,no,yes,50.0,Robert A. Chapek,www.thewaltdisneycompany.com,DIS,181438
Motor Vehicles & Parts,Ford Motor,22,-1.0,136341.0,17937.0,183000.0,Dearborn,MI,no,no,no,yes,21.0,James D. Farley Jr.,www.ford.com,F,50609
Retailing,Walmart,1,0.0,572754.0,13673.0,2300000.0,Bentonville,AR,no,no,no,yes,1.0,C. Douglas McMillon,https://www.stock.walmart.com,WMT,352037
Technology,Apple,3,0.0,365817.0,94680.0,154000.0,Cupertino,CA,no,no,no,yes,3.0,Timothy D. Cook,www.apple.com,AAPL,2443962
Telecommunications,AT&T,13,-2.0,168864.0,20081.0,202600.0,Dallas,TX,no,no,no,yes,11.0,John T. Stankey,www.att.com,T,148907
Transportation,United Parcel Service,34,1.0,97287.0,12890.0,400945.0,Atlanta,GA,no,no,yes,yes,35.0,Carol B. Tomé,www.ups.com,UPS,162355
Wholesalers,Sysco,70,-10.0,51297.8,524.2,57710.0,Houston,TX,no,no,no,yes,60.0,Kevin P. Hourican,www.sysco.com,SYY,44508

In [36]:
sectors.last()

,company,rank,rank_change,revenue,profit,num. of employees,city,state,newcomer,ceo_founder,ceo_woman,profitable,prev_rank,CEO,Website,Ticker,Market Cap
sector,,,,,,,,,,,,,,,,,
Aerospace & Defense,BWX Technologies,995,0.0,2124.1,305.9,6600.0,Lynchburg,VA,no,no,no,yes,,Rex D. Geveden,https://www.bwxt.com,BWXT,4925.6
Apparel,Crocs,954,0.0,2313.4,725.7,5770.0,Broomfield,CO,no,no,no,yes,,Andrew Rees,https://www.crocs.com,CROX,4811
Business Services,Harsco,991,0.0,2147.0,-3.2,12000.0,Camp Hill,PA,no,no,no,no,,F. Nicholas Grasberger III,https://www.harsco.com,HSC,969.7
Chemicals,Ashland,999,0.0,2111.0,220.0,4100.0,Wilmington,DE,no,no,no,yes,,Guillermo Novo,https://www.ashland.com,ASH,5601.9
Energy,Genesis Energy,994,0.0,2125.5,-165.1,1898.0,Houston,TX,no,no,no,no,,Grant E. Sims,https://www.genesisenergy.com,GEL,1435.4
Engineering & Construction,Beazer Homes USA,992,0.0,2140.3,122.0,1052.0,Atlanta,GA,no,no,no,yes,,Allan P. Merrill,https://www.beazer.com,BZH,478.8
Financials,Cowen,998,0.0,2112.8,295.6,1534.0,New York,NY,no,no,no,yes,,Jeffrey Solomon,https://www.cowen.com,COWN,1078
Food & Drug Stores,Grocery Outlet Holding,816,0.0,3079.6,62.3,875.0,Emeryville,CA,no,no,no,yes,,Eric J. Lindberg Jr.,https://www.groceryoutlet.com,GO,3148
"Food, Beverages & Tobacco",Brown-Forman,759,0.0,3461.0,903.0,4700.0,Louisville,KY,no,no,no,yes,,Lawson E. Whiting,https://www.brown-forman.com,BFB,31376.6
Health Care,Chemed,993,0.0,2139.3,268.6,14137.0,Cincinnati,OH,no,no,no,yes,,Kevin J. McNamara,https://www.chemed.com,CHE,7592.5
"Hotels, Restaurants & Leisure",Acushnet Holdings,990,0.0,2147.9,178.9,6500.0,Fairhaven,MA,no,no,no,yes,,David Maher,https://www.acushnetholdingscorp.com,GOLF,2914
Household Products,HNI,983,0.0,2184.4,59.8,8000.0,Muscatine,IA,no,no,no,yes,,Jeffrey D. Lorenger,https://www.hnicorp.com,HNI,1568.7
Industrials,Vizio Holding,996,0.0,2124.0,-39.4,800.0,Irvine,CA,no,yes,no,no,,William W. Wang,https://www.vizio.com,VZIO,1705.1
Materials,Century Aluminum,979,0.0,2212.5,-167.1,2512.0,Chicago,IL,no,no,no,no,,Jesse E. Gary,https://www.centuryaluminum.com,CENX,2400.3
Media,E.W. Scripps,962,0.0,2283.5,122.7,5600.0,Cincinnati,OH,no,no,no,yes,,Adam Symson,https://www.scripps.com,SSP,1154
Motor Vehicles & Parts,Cooper-Standard Holdings,952,0.0,2330.2,-322.8,21300.0,Northville,MI,no,no,no,no,,Jeffrey S. Edwards,https://www.cooperstandard.com,CPS,149
Retailing,1-800-Flowers.com,997,0.0,2122.2,118.7,4800.0,Jericho,NY,no,no,no,yes,,Christopher G. McCann,https://www.1800flowers.com,FLWS,830
Technology,DocuSign,1000,0.0,2107.2,-70.0,7461.0,San Francisco,CA,no,no,no,no,,Allan C. Thygesen,https://www.docusign.com,DOCU,21302.8
Telecommunications,Telephone & Data Systems,573,0.0,5329.0,156.0,8800.0,Chicago,IL,no,no,no,yes,,LeRoy T. Carlson Jr.,https://www.tdsinc.com,TDS,2163.4
Transportation,Kirby,971,0.0,2246.7,-247.0,5125.0,Houston,TX,no,no,no,no,,David W. Grzebinski,https://www.kirbycorp.com,KEX,4345.9
Wholesalers,Kar Auction Services,969,0.0,2251.6,66.5,8928.0,Carmel,IN,no,no,no,yes,,Peter J. Kelly,https://www.karglobal.com,KAR,2187.3

In [37]:
sectors.groups

{'Aerospace & Defense': [54, 57, 59, 93, 100, 205, 301, 369, 611, 623, 639, 697, 732, 861, 971, 980, 994], 'Apparel': [82, 379, 384, 457, 505, 539, 540, 545, 657, 753, 812, 884, 917, 922, 933, 953], 'Business Services': [142, 146, 166, 189, 202, 207, 226, 241, 254, 267, 313, 328, 352, 362, 406, 416, 469, 493, 509, 511, 573, 598, 607, 610, 616, 617, 648, 651, 662, 669, 674, 676, 677, 685, 714, 739, 803, 808, 828, 830, 852, 867, 881, 901, 915, 929, 965, 972, 974, 984, 986, 990], 'Chemicals': [63, 101, 174, 212, 217, 292, 304, 319, 321, 348, 349, 392, 405, 409, 491, 501, 517, 602, 615, 621, 765, 779, 786, 836, 940, 946, 948, 949, 998], 'Energy': [5, 15, 18, 28, 29, 53, 76, 87, 88, 98, 110, 129, 132, 134, 144, 152, 156, 167, 169, 192, 196, 214, 215, 218, 222, 223, 232, 238, 240, 242, 247, 256, 275, 277, 287, 307, 308, 314, 320, 332, 342, 343, 345, 346, 357, 361, 399, 413, 415, 430, 446, 450, 454, 468, 478, 484, 485, 499, 534, 543, 546, 557, 565, 568, 580, 618, 633, 638, 643, 701, 713, 715, 727, 730, 734, 750, 761, 767, 775, 780, 788, 806, 818, 820, 845, 848, 857, 858, 862, 869, 900, 904, 923, 941, 957, 964, 973, 979, 988, 993], 'Engineering & Construction': [123, 130, 258, 259, 261, 266, 284, 312, 356, 388, 396, 428, 452, 459, 542, 579, 587, 637, 672, 694, 700, 721, 748, 751, 754, 798, 811, 819, 822, 878, 921, 991], 'Financials': [6, 23, 32, 35, 40, 41, 43, 49, 50, 55, 56, 60, 65, 66, 71, 77, 78, 79, 84, 86, 89, 95, 96, 99, 102, 107, 125, 137, 149, 154, 158, 159, 160, 176, 177, 183, 184, 186, 187, 221, 228, 235, 237, 245, 246, 250, 255, 263, 265, 276, 280, 281, 288, 302, 315, 316, 317, 323, 324, 327, 335, 338, 344, 350, 355, 366, 367, 370, 371, 374, 375, 382, 383, 385, 386, 394, 397, 410, 414, 417, 421, 426, 433, 436, 441, 442, 448, 453, 463, 467, 472, 486, 488, 492, 502, 518, 520, 523, 531, 536, ...], 'Food & Drug Stores': [17, 20, 51, 75, 147, 519, 608, 671, 815], 'Food, Beverages & Tobacco': [37, 44, 80, 92, 94, 109, 120, 138, 164, 200, 231, 236, 257, 294, 295, 326, 330, 351, 381, 387, 402, 408, 425, 475, 504, 510, 559, 563, 622, 630, 656, 663, 729, 758], 'Health Care': [3, 4, 8, 9, 11, 14, 19, 25, 36, 39, 42, 61, 62, 70, 81, 85, 117, 121, 124, 128, 139, 172, 180, 194, 203, 213, 229, 230, 268, 291, 296, 298, 303, 318, 322, 337, 341, 360, 437, 439, 447, 512, 528, 538, 544, 550, 581, 583, 591, 599, 627, 642, 667, 687, 691, 693, 698, 744, 762, 797, 801, 814, 826, 834, 850, 851, 868, 872, 890, 903, 925, 928, 943, 975, 976, 977, 992], 'Hotels, Restaurants & Leisure': [119, 151, 269, 334, 358, 363, 449, 464, 489, 529, 537, 566, 661, 680, 688, 704, 718, 756, 770, 778, 781, 809, 810, 823, 847, 870, 950, 989], 'Household Products': [46, 181, 210, 211, 227, 329, 347, 412, 443, 458, 495, 553, 569, 585, 597, 614, 784, 825, 829, 896, 908, 926, 982], 'Industrials': [47, 72, 83, 104, 148, 161, 168, 198, 251, 252, 253, 262, 333, 427, 432, 438, 471, 549, 552, 578, 584, 606, 634, 640, 675, 678, 696, 705, 707, 712, 717, 722, 743, 745, 759, 766, 787, 792, 817, 837, 846, 859, 860, 885, 886, 909, 920, 938, 945, 995], 'Materials': [97, 163, 170, 171, 175, 191, 195, 260, 270, 271, 285, 311, 353, 400, 407, 411, 440, 451, 466, 483, 500, 533, 547, 548, 555, 558, 560, 561, 564, 567, 603, 625, 644, 679, 684, 731, 749, 795, 805, 874, 889, 905, 918, 936, 954, 978], 'Media': [52, 114, 115, 286, 309, 325, 373, 395, 507, 516, 551, 575, 595, 612, 636, 741, 769, 800, 816, 831, 841, 865, 873, 888, 911, 919, 934, 961], 'Motor Vehicles & Parts': [21, 24, 64, 150, 185, 201, 208, 243, 305, 390, 420, 586, 652, 709, 735, 736, 883, 939, 942, 951], 'Retailing': [0, 1, 10, 16, 31, 34, 67, 74, 105, 136, 140, 141, 143, 157, 173, 182, 188, 219, 220, 239, 244, 248, 264, 272, 274, 278, 289, 293, 299, 306, 336, 359, 376, 377, 378, 380, 389, 393, 401, 403, 419, 434, 444, 460, 461, 474, 479, 480, 487, 497, 508, 514, 525, 535, 589, 604, 641, 645, 658, 706, 719, 724, 738, 763, 773, 802, 804, 863, 880, 882, 897, 910, 930, 932, 981, 985, 996], 'Technology': [2, 7, 13, 26, 30, 45, 48, 58, 73, 90, 91, 106, 118, 122, 126, 127, 133, 135, 155, 165, 193, 197, 206, 209, 216, 225, 234, 249, 273, 300, 339, 340, 365, 372, 404, 422, 423, 424, 435, 455, 456, 462, 465, 470, 473, 481, 482, 494, 496, 503, 515, 521, 527, 530, 541, 556, 562, 570, 588, 594, 596, 600, 613, 620, 631, 632, 650, 653, 660, 665, 666, 673, 682, 683, 690, 703, 708, 711, 720, 723, 725, 728, 733, 737, 742, 757, 771, 777, 790, 796, 799, 807, 813, 827, 832, 833, 835, 838, 842, 843, ...], 'Telecommunications': [12, 22, 27, 68, 178, 204, 354, 498, 572], 'Transportation': [33, 38, 112, 113, 145, 153, 162, 224, 233, 290, 297, 310, 331, 364, 418, 429, 490, 513, 522, 526, 532, 554, 571, 577, 590, 647, 668, 686, 695, 702, 794, 891, 893, 960, 970], 'Wholesalers': [69, 103, 108, 111, 116, 131, 179, 190, 199, 279, 282, 283, 368, 391, 398, 431, 445, 476, 477, 506, 524, 576, 605, 664, 755, 772, 785, 789, 791, 854, 968]}

In [38]:
df.iloc[54,:]

company                     Lockheed Martin
rank                                     55
rank_change                            -6.0
revenue                             67044.0
profit                               6315.0
num. of employees                  114000.0
sector                  Aerospace & Defense
city                               Bethesda
state                                    MD
newcomer                                 no
ceo_founder                              no
ceo_woman                                no
profitable                              yes
prev_rank                              49.0
CEO                    James D. Taiclet Jr.
Website              www.lockheedmartin.com
Ticker                                  LMT
Market Cap                           103510
Name: 54, dtype: object

In [39]:
sectors.get_group('Apparel')

,company,rank,rank_change,revenue,profit,num. of employees,sector,city,state,newcomer,ceo_founder,ceo_woman,profitable,prev_rank,CEO,Website,Ticker,Market Cap
82,Nike,83,2.0,44538.0,5727.0,73300.0,Apparel,Beaverton,OR,no,no,no,yes,85.0,John J. Donahoe II,www.nike.com,NKE,171840
379,VF Corp.,380,-117.0,9238.8,407.9,33600.0,Apparel,Denver,CO,no,no,no,yes,263.0,Steven Rendle,https://www.vfc.com,VFC,11620
384,PVH,385,19.0,9154.7,952.3,25000.0,Apparel,New York,NY,no,no,no,yes,404.0,Stefan Larsson,https://www.pvh.com,PVH,5210
457,Hanesbrands,458,-26.0,7347.8,77.2,58000.0,Apparel,Winston-Salem,NC,no,no,no,yes,432.0,Stephen B. Bratspies,https://www.hanes.com,HBI,5191.4
505,Skechers U.S.A.,506,0.0,6310.2,741.5,8950.0,Apparel,Manhattan Beach,CA,no,yes,no,yes,,Robert Greenberg,https://www.skechers.com,SKX,6360.4
539,Levi Strauss,540,0.0,5763.9,553.5,16600.0,Apparel,San Francisco,CA,no,no,no,yes,,Charles Bergh,https://www.levistrauss.com,LEVI,5740
540,Tapestry,541,0.0,5746.3,834.2,14250.0,Apparel,New York,NY,no,no,yes,yes,,Joanne C. Crevoiserat,https://www.tapestry.com,TPR,9807.2
545,Under Armour,546,0.0,5683.5,360.1,12300.0,Apparel,Baltimore,MD,no,no,no,yes,,Colin Browne,https://https://about.underarmour.com,UAA,7712.4
657,Ralph Lauren,658,0.0,4400.8,-121.1,16200.0,Apparel,New York,NY,no,no,no,no,,Patrice Louvet,https://www.ralphlauren.com,RL,8073.2
753,Carter's,754,0.0,3486.4,339.7,15900.0,Apparel,Atlanta,GA,no,no,no,yes,,Michael D. Casey,https://www.carters.com,CRI,3763.4
812,Columbia Sportswear,813,0.0,3126.4,354.1,8325.0,Apparel,Portland,OR,no,no,no,yes,,Timothy P. Boyle,https://www.columbia.com,COLM,5840.4
884,G-III Apparel Group,885,0.0,2766.5,200.6,3250.0,Apparel,New York,NY,no,no,no,yes,,Morris Goldfarb,https://www.giii.com,GIII,1296.1
917,Deckers Outdoor,918,0.0,2545.6,382.6,3400.0,Apparel,Goleta,CA,no,no,no,yes,,David Powers,https://www.deckers.com,DECK,7457.8
922,Kontoor Brands,923,0.0,2475.9,195.4,14000.0,Apparel,Greensboro,NC,no,no,no,yes,,Scott H. Baxter,https://www.kontoorbrands.com,KTB,2325.3
933,Wolverine World Wide,934,0.0,2414.9,68.6,4400.0,Apparel,Rockford,MI,no,no,no,yes,,Brendan L. Hoffman,https://www.wolverineworldwide.com,WWW,1836.1
953,Crocs,954,0.0,2313.4,725.7,5770.0,Apparel,Broomfield,CO,no,no,no,yes,,Andrew Rees,https://www.crocs.com,CROX,4811

In [40]:
sectors.get_group('Apparel').shape

(16, 18)

In [49]:
sectors.mean(numeric_only=True)

,rank,rank_change,revenue,profit,num. of employees
sector,,,,,
Aerospace & Defense,491.941176,-9.470588,19940.117647,1241.000000,50423.529412
Apparel,642.375000,-7.625000,7332.068750,737.456250,19577.812500
Business Services,599.076923,-4.750000,7378.325000,1055.657692,29257.942308
Chemicals,525.137931,6.241379,10268.158621,1364.741379,17909.068966
Energy,472.310000,8.710000,18845.511000,1412.410101,8760.730000
Engineering & Construction,557.156250,-6.031250,7931.281250,655.093750,14652.406250
Financials,471.030120,-4.210843,17531.636747,3353.224096,22261.885542
Food & Drug Stores,325.777778,-3.222222,49665.166667,1114.833333,148315.000000
"Food, Beverages & Tobacco",356.000000,-11.676471,18162.961765,1852.438235,33008.264706
Health Care,446.909091,-2.155844,34912.179221,2720.031169,43949.116883
"Hotels, Restaurants & Leisure",617.500000,-1.750000,6731.171429,675.992857,75804.750000
Household Products,541.304348,-6.000000,10589.604348,1314.613043,26073.739130
Industrials,583.860000,-3.620000,10149.492000,862.008000,29125.980000
Materials,527.760870,11.695652,8661.530435,829.919565,16437.695652
Media,612.071429,-4.642857,9169.992857,694.253571,17098.555556
Motor Vehicles & Parts,468.200000,8.350000,23520.395000,2068.842105,52334.900000
Retailing,442.220779,2.272727,30648.937662,1647.216883,102182.012987
Technology,553.264463,-1.132231,18050.653719,3797.547934,35977.644628
Telecommunications,216.000000,-22.888889,58882.544444,8318.612500,76404.444444
Transportation,470.514286,6.885714,14377.694286,1130.528571,52608.914286
Wholesalers,440.516129,-0.612903,13074.906452,370.941935,15056.612903

In [50]:
sectors.sum(numeric_only=True)

,rank,rank_change,revenue,profit,num. of employees
sector,,,,,
Aerospace & Defense,8363,-161.0,338982.0,21097.0,857200.0
Apparel,10278,-122.0,117313.1,11799.3,313245.0
Business Services,31152,-247.0,383672.9,54894.2,1521413.0
Chemicals,15229,181.0,297776.6,39577.5,519363.0
Energy,47231,871.0,1884551.1,139828.6,876073.0
Engineering & Construction,17829,-193.0,253801.0,20963.0,468877.0
Financials,78191,-699.0,2910251.7,556635.2,3695473.0
Food & Drug Stores,2932,-29.0,446986.5,10033.5,1334835.0
"Food, Beverages & Tobacco",12104,-397.0,617540.7,62982.9,1122281.0
Health Care,34412,-166.0,2688237.8,209442.4,3384082.0
"Hotels, Restaurants & Leisure",17290,-49.0,188472.8,18927.8,2122533.0
Household Products,12450,-138.0,243560.9,30236.1,599696.0
Industrials,29193,-181.0,507474.6,43100.4,1456299.0
Materials,24277,538.0,398430.4,38176.3,756134.0
Media,17138,-130.0,256759.8,19439.1,461661.0
Motor Vehicles & Parts,9364,167.0,470407.9,39308.0,1046698.0
Retailing,34051,175.0,2359968.2,126835.7,7868015.0
Technology,66945,-137.0,2184129.1,459503.3,4353295.0
Telecommunications,1944,-206.0,529942.9,66548.9,687640.0
Transportation,16468,241.0,503219.3,39568.5,1841312.0
Wholesalers,13656,-19.0,405322.1,11499.2,466755.0

In [62]:
sectors['revenue'].mean().sort_values(ascending=False).head()  #top find resune

sector
Telecommunications        58882.544444
Food & Drug Stores        49665.166667
Health Care               34912.179221
Retailing                 30648.937662
Motor Vehicles & Parts    23520.395000
Name: revenue, dtype: float64