<a href="https://colab.research.google.com/github/ajaykumar080286/Pandas/blob/main/GroupBy_method.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd
import numpy as np

In [16]:
df=pd.read_csv('Fortune_1000.csv')

In [17]:
df.head()

,company,rank,rank_change,revenue,profit,num. of employees,sector,city,state,newcomer,ceo_founder,ceo_woman,profitable,prev_rank,CEO,Website,Ticker,Market Cap
0,Walmart,1,0.0,572754.0,13673.0,2300000.0,Retailing,Bentonville,AR,no,no,no,yes,1.0,C. Douglas McMillon,https://www.stock.walmart.com,WMT,352037
1,Amazon,2,0.0,469822.0,33364.0,1608000.0,Retailing,Seattle,WA,no,no,no,yes,2.0,Andrew R. Jassy,www.amazon.com,AMZN,1202717
2,Apple,3,0.0,365817.0,94680.0,154000.0,Technology,Cupertino,CA,no,no,no,yes,3.0,Timothy D. Cook,www.apple.com,AAPL,2443962
3,CVS Health,4,0.0,292111.0,7910.0,258000.0,Health Care,Woonsocket,RI,no,no,yes,yes,4.0,Karen Lynch,https://www.cvshealth.com,CVS,125204
4,UnitedHealth Group,5,0.0,287597.0,17285.0,350000.0,Health Care,Minnetonka,MN,no,no,no,yes,5.0,Andrew P. Witty,www.unitedhealthgroup.com,UNH,500468

In [18]:
sectors=df.groupby('sector')

In [19]:
sectors

In [23]:
len(df['sector'])

1000

In [24]:
len(df['company'])

1000

In [25]:
len(sectors)

21

In [28]:
sectors.size().sort_values(ascending=False)

sector
Financials                       166
Technology                       121
Energy                           100
Health Care                       77
Retailing                         77
Business Services                 52
Industrials                       50
Materials                         46
Transportation                    35
Food, Beverages & Tobacco         34
Engineering & Construction        32
Wholesalers                       31
Chemicals                         29
Hotels, Restaurants & Leisure     28
Media                             28
Household Products                23
Motor Vehicles & Parts            20
Aerospace & Defense               17
Apparel                           16
Food & Drug Stores                 9
Telecommunications                 9
dtype: int64

In [29]:
sectors.size().sort_values(ascending=False).head()  #top 5 company

sector
Financials     166
Technology     121
Energy         100
Health Care     77
Retailing       77
dtype: int64